### ISSUE TITLE
mixed specs in JSON

### ISSUE THREAD

**Issue by tischi** [mobie/htm-test#1]
I think here is a mix-up of specs.

https://github.com/mobie/htm-test/blob/4afad6635af49266f773f4d2e1ee8260547a01e7/data/example-dataset/dataset.json#L2648

For the purpose of this repo, `"-nuclei_plate_segmentation-nuclei" I would think  should be removed.

**Comment by constantinpape** [comment]
Yep, I forgot to update the python library on the EMBL server before running the script. It's fixed now.
